"""Add provenance fields for Phase 9

Revision ID: 065468cac112
Revises: 47eb9df50f50
Create Date: 2026-09-29 00:34:18.322639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065468cac112'
down_revision: Union[str, Sequence[str], None] = '47eb9df50f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dgca_monthly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dataset_version', sa.String(length=50), nullable=True))

    with op.batch_alter_table('fares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dataset_version', sa.String(length=50), nullable=True))

    with op.batch_alter_table('index_daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dataset_version', sa.String(length=50), nullable=True))

    with op.batch_alter_table('weights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dataset_version', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weights', schema=None) as batch_op:
        batch_op.drop_column('dataset_version')
        batch_op.drop_column('source_reference')

    with op.batch_alter_table('index_daily', schema=None) as batch_op:
        batch_op.drop_column('dataset_version')
        batch_op.drop_column('source_reference')

    with op.batch_alter_table('fares', schema=None) as batch_op:
        batch_op.drop_column('dataset_version')
        batch_op.drop_column('source_reference')

    with op.batch_alter_table('dgca_monthly', schema=None) as batch_op:
        batch_op.drop_column('dataset_version')
        batch_op.drop_column('source_reference')

    # ### end Alembic commands ###
