"""phase 7 schema update

Revision ID: 47eb9df50f50
Revises: 55476d09fa45
Create Date: 2026-09-29 00:21:51.986689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47eb9df50f50'
down_revision: Union[str, Sequence[str], None] = '55476d09fa45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_quote_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_mode', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_fares_raw_quote_id', 'raw_quotes', ['raw_quote_id'], ['id'])

    with op.batch_alter_table('dgca_monthly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))

    with op.batch_alter_table('index_daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('weight_version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('methodology_version', sa.String(length=20), nullable=True))

    with op.batch_alter_table('weights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('methodology', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weights', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('effective_to')
        batch_op.drop_column('effective_from')
        batch_op.drop_column('methodology')
        batch_op.drop_column('source')
        batch_op.drop_column('data_mode')

    with op.batch_alter_table('index_daily', schema=None) as batch_op:
        batch_op.drop_column('methodology_version')
        batch_op.drop_column('weight_version')
        batch_op.drop_column('data_mode')

    with op.batch_alter_table('fares', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
