"""init APIx schema

Revision ID: 55476d09fa45
Revises: 
Create Date: 2026-09-29 00:11:43.733346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55476d09fa45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dgca_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('sector', sa.String(length=10), nullable=False),
    sa.Column('avg_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dgca_monthly_id'), 'dgca_monthly', ['id'], unique=False)
    op.create_table('index_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('variant', sa.String(length=20), nullable=True),
    sa.Column('route_id', sa.String(length=10), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_daily_id'), 'index_daily', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('dest', sa.String(length=3), nullable=False),
    sa.Column('dgca_pax_share', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('robots_ok', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('fares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=10), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=False),
    sa.Column('flight_no', sa.String(length=20), nullable=True),
    sa.Column('dep_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dep_bucket', sa.String(length=20), nullable=True),
    sa.Column('lead_days', sa.Integer(), nullable=True),
    sa.Column('fare_class', sa.String(length=20), nullable=True),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('udf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conv_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_outlier', sa.Boolean(), nullable=True),
    sa.Column('is_soldout', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fares_id'), 'fares', ['id'], unique=False)
    op.create_table('raw_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('payload_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_quotes_id'), 'raw_quotes', ['id'], unique=False)
    op.create_table('weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('route_id', sa.String(length=10), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('lead_days', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weights_id'), 'weights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weights_id'), table_name='weights')
    op.drop_table('weights')
    op.drop_index(op.f('ix_raw_quotes_id'), table_name='raw_quotes')
    op.drop_table('raw_quotes')
    op.drop_index(op.f('ix_fares_id'), table_name='fares')
    op.drop_table('fares')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_index_daily_id'), table_name='index_daily')
    op.drop_table('index_daily')
    op.drop_index(op.f('ix_dgca_monthly_id'), table_name='dgca_monthly')
    op.drop_table('dgca_monthly')
    # ### end Alembic commands ###
